/**
 * Created by amit on 9/24/17.
 */


export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const LOAD_SELECTED_CATEGORY = 'LOAD_SELECTED_CATEGORY';
export const LOAD_SELECTED_CATEGORY_POSTS = 'LOAD_SELECTED_CATEGORY_POSTS';
export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';


