/**
 * Created by amit on 9/24/17.
 */


export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const LOAD_SELECTED_CATEGORY = 'LOAD_SELECTED_CATEGORY';
export const LOAD_SELECTED_CATEGORY_POSTS = 'LOAD_SELECTED_CATEGORY_POSTS';
export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';
export const OPEN_EDIT_POST = 'OPEN_EDIT_POST';
export const POST_DIALOG_CLOSED_CLICKED = 'POST_DIALOG_CLOSED_CLICKED';
export const UP_VOTE_POST = 'UP_VOTE_POST';
export const DOWN_VOTE_POST = 'DOWN_VOTE_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_POST = 'DELETE_POST';

