/**
 * Created by amit on 9/24/17.
 */


export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const LOAD_SELECTED_CATEGORY = 'LOAD_SELECTED_CATEGORY';
export const LOAD_SELECTED_CATEGORY_POSTS = 'LOAD_SELECTED_CATEGORY_POSTS';
export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';
export const OPEN_EDIT_POST = 'OPEN_EDIT_POST';
export const OPEN_CREATE_POST_DIALOG = 'OPEN_CREATE_POST_DIALOG';
export const POST_DIALOG_CLOSED_CLICKED = 'POST_DIALOG_CLOSED_CLICKED';
export const UP_VOTE_POST = 'UP_VOTE_POST';
export const DOWN_VOTE_POST = 'DOWN_VOTE_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_POST = 'DELETE_POST';
export const CREATE_NEW_POST = 'CREATE_NEW_POST';
export const CREATE_NEW_COMMENT = 'ADD_NEW_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const UPDATE_EXISTING_COMMENT = 'UPDATE_EXISTING_COMMENT';
export const UP_VOTE_COMMENT = 'UP_VOTE_COMMENT';
export const DOWN_VOTE_COMMENT = 'DOWN_VOTE_COMMENT';
export const OPEN_CREATE_COMMENT_DIALOG = 'OPEN_CREATE_COMMENT_DIALOG';
export const COMMENT_DIALOG_CLOSED_CLICKED = 'COMMENT_DIALOG_CLOSED_CLICKED';
export const LOAD_COMMENTS = 'LOAD_COMMENTS';

